### ISSUE TITLE
Compilation failed to when trying to run the storybook

### ISSUE THREAD

**Issue by arielsardinha** [widgetbook/widgetbook#685] opened 2023-05-21 01:07 UTC
**Description**
Compilation failed to when trying to run the storybook.

**Steps To Reproduce**
when running flutter run

**Screenshots**
https://media.discordapp.net/attachments/509072449695121434/1109647005250236456/image.png?width=816&height=400

**Comment by YoussefRaafatNasry** [comment] 2023-05-22 13:15
duplicate of #672

**Closed by YoussefRaafatNasry** 2023-05-22 13:15 UTC
