### ISSUE TITLE
Can not select knob option that is a list with 2 items

### ISSUE THREAD

**Issue by jtdLab** [widgetbook/widgetbook#1179] opened 2024-05-23 17:14 UTC
**Description**
Can not select knob list options with 2 items.

**Steps To Reproduce**

 1.
```dart
 final favoriteFinishes = context.knobs.list(
    label: 'Favorite Finishes',
    options: [
      const <int>[],
      const [16],
      const [16, 32],
      const [16, 32, 40],
    ],
    initialOption: const [16, 32, 40],
  );
```

2. Select the option with length 2.

**Expected Behavior**
Select it and update the widget.

**Additional Context**
With 0,1 and 3 items it works 

Error Logs:

```sh
╞═══════════════════════════════════════════════════════════
The following IndexError was thrown building:
RangeError (index): Index out of range: index should be less than 1: 1

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/js_array.dart 592:7                 _get]
packages/widgetbook/src/fields/field_codec.dart 42:42                             <fn>
dart-sdk/lib/internal/iterable.dart 425:31                                        elementAt
dart-sdk/lib/internal/iterable.dart 354:26                                        moveNext
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 918:20  next
dart-sdk/lib/collection/maps.dart 89:14                                           addEntries
dart-sdk/lib/core/map.dart 210:17                                                 <fn>
dart-sdk/lib/core/map.dart 210:35                                                 fromEntries
packages/widgetbook/src/fields/field_codec.dart 38:12
decodeQueryGroup
packages/widgetbook/src/fields/field.dart 61:33                                   build
packages/widgetbook/src/knobs/knob.dart 70:29                                     <fn>
dart-sdk/lib/internal/iterable.dart 425:31                                        elementAt
dart-sdk/lib/internal/iterable.dart 354:26                                        moveNext
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 918:20  next
dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 483:14                of
dart-sdk/lib/internal/iterable.dart 224:7                                         toList
packages/widgetbook/src/knobs/knob.dart 70:45                                     buildFields
packages/widgetbook/src/layout/responsive_layout.dart 46:28                       <fn>
dart-sdk/lib/internal/iterable.dart 403:20                                        moveNext
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 918:20  next
dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 483:14                of
dart-sdk/lib/core/iterable.dart 497:7                                             toList
packages/widgetbook/src/layout/responsive_layout.dart 46:48                       buildKnobs
packages/widgetbook/src/settings/settings_panel.dart 27:41                        <fn>
packages/flutter/src/widgets/scroll_delegate.dart 490:22                          build
packages/flutter/src/widgets/sliver.dart 831:18                                   [_build]
packages/flutter/src/widgets/sliver.dart 761:67
processElement
dart-sdk/lib/core/iterable.dart 347:29                                            forEach
packages/flutter/src/widgets/sliver.dart 808:18
performRebuild
packages/flutter/src/widgets/framework.dart 5203:7                                rebuild
packages/flutter/src/widgets/framework.dart 2905:18                               buildScope
packages/flutter/src/widgets/binding.dart 1136:9                                  drawFrame
packages/flutter/src/rendering/binding.dart 443:5
[_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1392:7
[_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1313:9
handleDrawFrame
packages/flutter/src/scheduler/binding.dart 1171:5
[_handleDrawFrame]
lib/_engine/engine/platform_dispatcher.dart 1404:5                                invoke
lib/_engine/engine/platform_dispatcher.dart 307:5
invokeOnDrawFrame
lib/_engine/engine/initialization.dart 187:36                                     <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 426:37
_checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 431:39  dcall
══════════════════════════════════════════════════════════════════════════════════════════════
══════
Another exception was thrown: RangeError (index): Index out of range: index should be less
than 1: 1
Another exception was thrown: RangeError (index): Index out of range: index should be less
than 1: 1
Another exception was thrown: RangeError (index): Index out of range: index should be less
than 1: 1
Another exception was thrown: RangeError (index): Index out of range: index should be less
than 1: 1
Another exception was thrown: RangeError (index): Index out of range: index should be less
than 1: 1

```

**Comment by YoussefRaafatNasry** [comment] 2024-05-27 14:43
Hello @jtdLab 👋 

Thanks for reporting this issue!
I was able to reproduce it on my side, and it turns out that it's caused by the commas.
It happened before with `string` knobs and was fixed in #817.

As a quick workaround for now, you can change how the knob's value is encoded/decoded as follows. _Unfortunately this will affect the label of the dropdown as well._

```dart
final favoriteFinishes = context.knobs.list(
  label: 'Favorite Finishes',
  labelBuilder: (value) => value.join('-'),
  initialOption: const [16, 32, 40],
  options: [
    const <int>[],
    const [16],
    const [16, 32],
    const [16, 32, 40],
  ],
);
```

The proper fix would be to use URL encoding/decoding for knobs' values (similar to what we did with knobs' labels in #1165). This will help prevent the issue from happening with other knobs as well.

Would you like to contribute to Widgetbook by submitting a PR for that fix?

**Comment by yunweneric** [comment] 2024-06-22 19:38
Hi @YoussefRaafatNasry 

I will like to work on this issue.

**Comment by YoussefRaafatNasry** [comment] 2024-06-25 08:16
Great, @yunweneric!
Looking forward for the PR 👀

**Comment by yunweneric** [comment] 2024-06-25 10:09
Awesome 😎

**Comment by yunweneric** [comment] 2024-07-05 08:01
Hi @YoussefRaafatNasry 

I noticed the bug is on this line. I don't know exactly what it does for other components but i see it affects the commas used to separate list items

``` static Map<String, String> decodeQueryGroup(String? group) {
    if (group == null) return {};

  ------>  final params = group.substring(1, group.length - 1).split(',');

    return Map<String, String>.fromEntries(
      params.map(
        (param) {
          final parts = param.split(':');
          final String decodedKey = Uri.decodeComponent(parts[0]);
          return MapEntry(decodedKey, parts[1]);
        },
      ),
    );
  }


```

`group = "{mylist:[Shoe, Bags, Headsets]}"`

## My thoughts

### Since the split method will affect every comma seperated value, we could:
- Get the get the list items (my_list in my case) and encode before the split method then decode thereafer
- Format the listitems before we reach the `decodeQueryGroup` method of this class probably in the `KnobsExtension` extension
- use a different **symbol** for the split method that could not be used **in strings**. PS: this is incase removing it will not affect an implementation elsewhere


Please let me know what you think.
Cheers

**Comment by YoussefRaafatNasry** [comment] 2024-07-08 08:59
Hello @yunweneric 👋 

Great analysis of the problem. The most solution that I am in favor of is the first one you have mentioned, which is encoding and decoding the fields' values before "groupping" them.

We have use the URL encoding before in #817 and #1165 to get around this problem with string knobs and knobs' labels respectively. But now, we are looking into a more global fix that will prevent this from happening in the future again for all other knobs and special characters (e.g. colons and curly braces can be problematic too).

The encoding/decoding process will look something like this

```dart
//// Encoding ////

final queryGroup = {
  'listKnob': '[16, 32]', // from the original issue
  'stringKnob': 'something:or not', // with colons and spaces
};

final encoded = FieldCodec.encodeQueryGroup(queryGroup);
print(encoded); // {listKnob:%5B16%2C%2032%5D,stringKnob:something%2Cor%20not}



//// Decoding ////

final params = encoded.substring(1, group.length - 1).split(',');
final decodedGroup = Map<String, String>.fromEntries(
  params.map(
    (param) {
      final parts = param.split(':');
      final decodedKey = Uri.decodeComponent(parts[0]);
      final decodedValue = Uri.decodeComponent(parts[1]);

      return MapEntry(decodedKey, decodedValue);
    },
  ),
);

print(decodedGroup); 
// {
//   'listKnob': '[16, 32]',
//   'stringKnob': 'something:or not',
// }
```

With that change, we can also revery the change done in #817, as it will be redundant.

**Comment by yunweneric** [comment] 2024-07-08 09:55
Hi @YoussefRaafatNasry 

Thank you for finding time to look at this. I will do this fix and submit a PR ASAP

**Comment by YoussefRaafatNasry** [comment] 2024-07-22 14:54
Hello @yunweneric 👋 

We have submitted a fix for this as it was [blocking](https://github.com/widgetbook/widgetbook/pull/1211#pullrequestreview-2191464973) another contribution.

Looking forward to your contribution in any of the other open issues instead!

**Closed** 2024-07-22 14:54 UTC
Labels: t: bug, p: core, m: knobs

**Comment by yunweneric** [comment] 2024-07-22 15:51
Thank you for notifying me. I will look for another issue and work on it
