### ISSUE TITLE
fix: cannot set URL strategy more than once

### ISSUE THREAD

**Issue by sami-samcla** [widgetbook/widgetbook#61] opened 2021-11-08 12:02 UTC
Hi.

I'm trying to create a simple example with widgetbook (**version 1.0.1**) package, but it's impossible.

When I try to launch the app to chrome, throw this error:

_EXCEPTION CAUGHT BY WIDGETS LIBRARY_ 
The following assertion was thrown building HotReload:
Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/window.dart:25:10
!_isUrlStrategySet
_"Cannot set URL strategy more than once."_

_The relevant error-causing widget was:
  HotReload
  HotReload:file:///Users/sissa/StudioProjects/flutter/infinite_hub/lib/stories/main.dart:16:19_

I launch the app with `flutter run -t lib/stories/main.dart -d chrome`

**My lib/stories/main.dart file**:
```
void main() {
  runApp(HotReloadClass());
}

class HotReloadClass extends StatelessWidget {
  HotReloadClass({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: getAppTheme(),
      home: const HotReload(),
    );
  }
}
```
**The widgetBook file:**
```
import 'package:flutter/material.dart';
import 'package:infinite_hub/customviews/empty_result_widget.dart';
import 'package:widgetbook/widgetbook.dart';

class HotReload extends StatelessWidget {
  const HotReload({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Widgetbook(
      appInfo: AppInfo(name: 'Infinite HUB Widgets'),
      lightTheme: ThemeData.light(),
      darkTheme: ThemeData.dark(),
      categories: [
        WidgetbookCategory(name: 'widgets', widgets: [
          WidgetbookWidget(
            name: 'EmptyResultWidget',
            useCases: [
              WidgetbookUseCase(
                  name: 'Empty result',
                  builder: (context) => EmptyResultWidget(
                        title: 'Test widget book',
                        icon: Icons.clear,
                        baseColor: Colors.blueGrey,
                        onRefresh: () {},
                      ))
            ],
          )
        ]),
      ],
    );
  }
}
```

**The custom widget:**
```
import 'package:flutter/material.dart';
import 'package:flutter/painting.dart';

class EmptyResultWidget extends StatelessWidget {
  final IconData icon;
  final String title;
  final Color baseColor;
  final Function onRefresh;

  EmptyResultWidget({this.title, this.icon, this.baseColor, this.onRefresh});

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.center,
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          Icon(
            icon,
            color: baseColor,
            size: 100,
          ),
          SizedBox(
            height: 12.0,
          ),
          Text(
            title,
            style: TextStyle(
              fontWeight: FontWeight.bold,
              fontSize: 24.0,
              color: baseColor,
            ),
            textAlign: TextAlign.center,
          ),
          SizedBox(height: 20.0),
          null != onRefresh
              ? IconButton(
                  onPressed: onRefresh,
                  icon: Icon(
                    Icons.add,
                    color: Colors.blueGrey,
                  ),
                  iconSize: 30,
                )
              : SizedBox()
        ],
      ),
    );
  }
}
```

**My Futter doctor report:**
```
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.5.2 20G95 darwin-x64, locale en-GB)
    • Flutter version 2.5.2 at /Users/sissa/fvm/versions/2.5.2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (6 weeks ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/sissa/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • ANDROID_HOME = /Users/sissa/Library/Android/sdk
    • Java binary at: /Applications/Android Studio 2.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.40.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.5.2 20G95 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```

Thanks in advance.

**Comment by kwstasarva** [comment] 2022-01-13 14:52
Hello @sami-samcla. The problem is that you are wrapping Widgetbook with MaterialApp. I am having the same issue as well. Once I remove the MaterialApp, widgetbook is being displayed correctly. This seems to be a bug. For the time being, you can remove MaterialApp and it will work.

**Comment by jenshor** [comment] 2023-02-07 08:46
I tested this with `widgetbook` `3.0.0-beta.x` and the problem does not occur. While we currently have no updated docs or migration docs, I'll close this issue as the problem does not longer seem to exist. 

If you have additional feedback, feel free to re-open the issue.

**Closed by jenshor** 2023-02-07 08:46 UTC
Labels: bug

**Comment by sami-samcla** [comment] 2023-02-07 09:20
Thanks @jenshor for your feedback. I'll check when I have time to it!! Nice work!!
