### ISSUE TITLE
Problem in package of GoRouter and navigation_panel

### ISSUE THREAD

**Issue by raghvind-yadav** [widgetbook/widgetbook#684] opened 2023-05-19 16:11 UTC
After getting update of flutter to 3.10.1 from 3.7.0, I was running my widget book I was keep running into this error.
```
../../../../../.pub-cache/hosted/[pub.dev](http://pub.dev/)/go_router-3.1.1/lib/src/go_router.dart:22:44: Error: The class 'NavigatorObserver' can't be used as a mixin because it isn't a mixin class nor a mixin.
class GoRouter extends ChangeNotifier with NavigatorObserver {
                                           ^
../../../../../.pub-cache/hosted/pub.dev/widgetbook-2.4.1/lib/src/navigation/navigation_panel.dart:49:17: Error: 'SearchBar' is imported from both 'package:flutter/src/material/search_anchor.dart' and 'package:widgetbook/src/widgets/search_bar.dart'.
          const SearchBar(),
                ^^^^^^^^^
```
So, there are two error. I fixed it but I don't know it was right or wrong.
For 1st error, I open the file of go_router.dart and just swap ChangeNotifier and NavigatorObserver in GoRouter class declartion line.
intial :```
 class GoRouter extends ChangeNotifier with NavigatorObserver {
	............................
	}
```
changed to: ```
class GoRouter extends NavigatorObserver with ChangeNotifier {
	.............................
	}
```
file location of go_router.dart : C:/Users/XXXX/AppData/Local/Pub/Cache/hosted/pub.dev/go_router-3.1.1/lib/src/go_router.dart)
For 2nd error, I open the file  of navigation_panel.dart and comment the import line of `"package:widgetbook/src/widgets/search_bar.dart".`
This works for me.
file location of navigation_panel.dart : C:\Users\XXXX\AppData\Local\Pub\Cache\hosted\pub.dev\widgetbook-2.4.1\lib\src\navigation\navigation_panel.dart

After doing that I am not facing any problem in widget book.

**Comment by YoussefRaafatNasry** [comment] 2023-05-19 16:20
Duplicate of #672

**Closed by YoussefRaafatNasry** 2023-05-19 16:20 UTC
