### ISSUE TITLE
Change Twitter logo to X

### ISSUE THREAD

**Issue by blindaks** [widgetbook/widgetbook#978] opened 2023-10-10 19:18 UTC
**Description**
A description of what the bug is.
Twitter is now X, and so must be its logo on the website

**Steps To Reproduce**

1. Go to ...
2. Click on ....
3. Scroll down to ....

**Expected Behavior**
A description of what you expected to happen.

**Screenshots**
![image](https://github.com/widgetbook/widgetbook/assets/128223364/9d2d5bf0-7865-403e-83b2-567e6daaf50c)

**Additional Context**

**Comment by blindaks** [comment] 2023-10-10 19:18
I would like to work on this issue. Please assign it to me.

**Comment by YoussefRaafatNasry** [comment] 2023-10-11 08:37
Duplicate of #928

**Closed by YoussefRaafatNasry** 2023-10-11 08:37 UTC
