### ISSUE TITLE
Show/Hide Side Panels

### ISSUE THREAD

**Issue by mjablecnik** [widgetbook/widgetbook#748] opened 2023-06-14 10:10 UTC
Can you add buttons for show/hide left and right panels?

**Comment by Mujhtech** [comment] 2023-10-04 15:38
@YoussefRaafatNasry I would like to work on this issue

**Comment by vaishnavi-2307** [comment] 2023-10-08 14:35
@YoussefRaafatNasry  can you please assign this issue to me, i would love to work on this issue and learn from it.

**Comment by Anurag-space** [comment] 2023-10-19 02:14
@YoussefRaafatNasry 
i would like to work to this issue.Could you please assign me this issue.

**Comment by YoussefRaafatNasry** [comment] 2023-10-24 09:23
Duplicate of #805

**Closed by YoussefRaafatNasry** 2023-10-24 09:24 UTC
Labels: t: feat, p: core, hacktoberfest
