### ISSUE TITLE
Update the Twitter Logo to X

### ISSUE THREAD

**Issue by Hemant2335** [widgetbook/widgetbook#991] opened 2023-10-15 07:44 UTC
**Description**
The logo of twitter has been changed to X but has not been updated in your website 

**Steps To Reproduce**

1. Go to https://www.widgetbook.io/
3. Scroll down to footer

**Expected Behavior**
the updated X logo should be there

**Screenshots**
![Screenshot (270)](https://github.com/widgetbook/widgetbook/assets/85656999/5adc0e9c-7b22-465d-a8f4-7f15b9b6e6bb)

**Comment by Hemant2335** [comment] 2023-10-15 07:44
Please assign this issue to me

**Comment by YoussefRaafatNasry** [comment] 2023-10-16 08:37
Duplicate of #928

**Closed** 2023-10-16 08:37 UTC
