### ISSUE TITLE
Question: widgetbook_generator with multiple packages

### ISSUE THREAD

**Issue by mpoimer** [widgetbook/widgetbook#1251] opened 2024-08-30 12:02 UTC
Hi,

I am trying to generate use cases from multiple local packages inside my flutter project into a widgetbook package and am making good progress, but it seems like the imports in the `*.directories.g.dart` file are not generated correctly.

My folder structure looks as follows:

![image](https://github.com/user-attachments/assets/790ad59b-218a-4219-9e41-b6a9e8360029)

and my build.yaml in the root folder looks like this:

```yaml
targets:
  $default:
    dependencies:
      - main_app
    sources:
      # --
      # Note that it is important to include these in the default target.
      - pubspec.*
      - $package$
      - lib/$lib$
      # --
      - widgetbook/lib/main.dart
      - lib/**
      - main_app
    builders:
      widgetbook_generator:use_case_builder:
        generate_for:
          - lib/**
          - main_app/lib/**
```

This works perfectly fine with the only issue that the imports are not `'package:main_app/widgets/...'` but rather `'../../main_app/lib/widgets/...'`, which does not work.

I have also tried it by prefixing `main_app` with `package:main_app`, but then the directories is missing the widgets from `main_app`.

```yaml
targets:
  $default:
    dependencies:
      - main_app
    sources:
      # --
      # Note that it is important to include these in the default target.
      - pubspec.*
      - $package$
      - lib/$lib$
      # --
      - widgetbook/lib/main.dart
      - lib/**
      - package:main_app/lib/**
    builders:
      widgetbook_generator:use_case_builder:
        generate_for:
          - lib/**
          - package:main_app/lib/**
```   

Am I missing something here or doing something wrong with the `package main_app`?

Any help would be greatly appreciated!

Thanks

**Comment by yousinix** [comment] 2024-09-02 11:56
Hello @mpoimer 👋 

I believe this is happening due to #829. We use the `pubspec.lock` to resolve the paths that are used later for imports. To be able to debug this further from our side, please provide us with a minimal reproduction repo.

On the other hand, I would recommend following the structure mentioned [here](https://widgetbook.docs.page/widgetbook/guides/quick-start), where you will have one `widgetbook` package, that imports all the other apps, and the `widgetbook_generator` is used only in the package.

**Comment by yousinix** [comment] 2024-09-04 12:51
Thanks for the reproduction repo, @mpoimer 👋 

After investigating this more, it turns out that this is happening because the analyzer considers all the files **outside** the `lib` directory, _of the package that the `build_runner` is running on,_ to be **assets**. In your case, here's what happens:
1. The input file is `main_app/lib/app/widgets/outlined_loading_button.dart`.
1. The URI for the element is `asset:widgetbook_example/main_app/lib/app/widgets/outlined_loading_button.dart` while [resolving the `importUri`](https://github.com/widgetbook/widgetbook/blob/25ecf910e26101fd41ee90768cef3c76a25fbff8/packages/widgetbook_generator/lib/src/generators/use_case_generator.dart#L110-L113).
1. The `asset:` URI is later converted to a local path when generating the directories list.

Technically, we can do some magic to resolve the `asset:` imports to `package:` imports in some cases. But such a case feels a bit odd, and we are not planning on supporting it in the meantime, unless their is a strong/common need for it.

I would suggest that you go with the following structure that can help you port your Widgetbook to Widgetbook Cloud easily in the future.

```tree
widgetbook_example/
├── lib/
│   └── app/widgets/
│       └── elevated_loading_button.dart (ElevatedLoadingButton widget only)
├── main_app/
│   └── lib/
│       └── app/widgets/
│           └── outlined_loading_button.dart (OutlinedLoadingButton widget only)
└── widgetbook/
    ├── pubspec.yaml (generator and annotation packages are only needed here)
    └── lib/
        ├── widgetbook_example/
        │   └── elevated_loading_button.usecases.dart (use-cases of ElevatedLoadingButton)
        └── main_app/
            └── outlined_loading_button.usecases.dart (use-cases of OutlinedLoadingButton)
```

I will be closing this issue for now as "not planned", but we are happy to listen to your feedback are re-consider opening it in the future.

**Closed by yousinix** 2024-09-04 12:51 UTC
Labels: t: bug, p: generator
