### ISSUE TITLE
Request to Update Twitter Logo

### ISSUE THREAD

**Issue by moheyt** [widgetbook/widgetbook#1010] opened 2023-10-25 16:47 UTC
**Description**
I have identified that the Twitter logo displayed in the footer section of website is outdated, and it is crucial to keep branding up to date with the latest elements provided by Twitter.

**Steps To Reproduce**

1. Go to Homepage
2. Scroll down the bottom

**Expected Behavior**
New Twitter logo will be used to replace the outdated one in the footer section of our website.

**Screenshots**
![Screenshot 2023-10-25 221616](https://github.com/widgetbook/widgetbook/assets/85775976/31db3ab5-39c9-491b-aee4-4545079323a1)

![Screenshot 2023-10-25 221651](https://github.com/widgetbook/widgetbook/assets/85775976/ee75388f-cca3-4209-b7ef-bab98568a593)

**Additional Context**
N/A

**Comment by moheyt** [comment] 2023-10-25 16:52
I would like to work on this. Can you assign it to me? #hacktoberfest

**Comment by YoussefRaafatNasry** [comment] 2023-10-26 08:03
Duplicate of #928

**Closed by YoussefRaafatNasry** 2023-10-26 08:03 UTC
