### ISSUE TITLE
Problem with material theme extensions

### ISSUE THREAD

**Issue by andrewpmoore** [widgetbook/widgetbook#1284] opened 2024-10-09 09:27 UTC
**Description**
I'm defining theme extension for the components I'm working on

e.g
```
extensions: <ThemeExtension<dynamic>>[
		gapThemeDesktopExtension,
    ]


IhGapExtension gapThemeDesktopExtension = const IhGapExtension(
  small1: Spacing.p8,
  small2: Spacing.p12,
  small3: Spacing.p16,
  small3Uni: Spacing.p12,
  small4: Spacing.p20,
  small4Variant: Spacing.p28,
  medium1: Spacing.p24,
  medium2: Spacing.p28,
  medium3: Spacing.p32,
  medium4: Spacing.p36,
  large1: Spacing.p40,
  large2: Spacing.p44,
  large3: Spacing.p48,
  large4: Spacing.p52,
  extraLarge1: Spacing.p56,
  extraLarge2: Spacing.p60,
  extraLarge3: Spacing.p64,
  extraLarge4: Spacing.p68,
);
```

If I then use the following
```
Theme.of(context).extension<IhGapExtension>()!.small4
```

I get `Null check operator used on a null value`

If I'm not using widgetbook I don't get this error.

**Steps To Reproduce**
```
    return MaterialApp(
      theme: lightTheme(context),
      home: SafeArea(
        child: Widgetbook.material(
          lightTheme: lightTheme(context),
            AlignmentAddon(),
          ],
          directories: [
            WidgetbookFolder(
              name: 'Texts',
              children: [
                WidgetbookComponent(
                  name: 'Size',
                  useCases: [
                    WidgetbookUseCase(
                      name: 'Default',
                      builder: (context) => Container(width: Theme.of(context).extension<IhGapExtension>()!.small4,)
                    ),
                  ],
                ),
              ],
            ),
          ],
        ),
      ),
    );
```

**Expected Behavior**
I don't expect the null exception and expect for the gap details to be obtained
If it's not wrapped in widgetbook, then the gap extension is ok and can be found

**Comment by yousinix** [comment] 2024-10-09 10:53
Hello @andrewpmoore 👋 

It looks like you are using `Widgetbook.themeLight` to provide a theme for your use-cases.
This field is used to customize the look of Widgetbook itself.

To make your theme available for your use-cases, you should use a [`MaterialThemeAddon`](https://docs.widgetbook.io/addons/theme-addon#material-theme-addon) as follows:

```dart
return Widgetbook.material(
  addons: [
    MaterialThemeAddon(
      themes: [yourLightTheme]
    ),
  ],
  directories: [ ... ],
);
```

I will close this issue for now, if the above solution didn't work for you, please provide us with full reproduction code and I will reopen the issue again.

**Comment by andrewpmoore** [comment] 2024-10-09 15:22
Here's a complete example, I notice it only seems to happen if I push to a new route in the widget. You'll see padding using the Gap extension on the first page, but after pressing the `press me` button you'll get the `NullPointerException` on the same code on the next page.

```
import 'package:flutter/material.dart';
import 'package:ui_components/ui_components.dart';
import 'package:widgetbook/widgetbook.dart';

import 'main.dart';

void main() {
  runApp(const HotReload());
}

class HotReload extends StatefulWidget {
  const HotReload({super.key});

  @override
  State<HotReload> createState() => _HotReloadState();
}

class _HotReloadState extends State<HotReload> {
  @override
  Widget build(BuildContext context) {
    return Widgetbook.material(
      addons: [
        MaterialThemeAddon(
            themes: [
              WidgetbookTheme(
                name: 'Light',
                data: lightTheme(context),
              ),
            ]
        ),

      ],
      directories: [
        WidgetbookFolder(
          name: 'Example',
          children: [
            WidgetbookComponent(
              name: 'Text',
              useCases: [
                WidgetbookUseCase(
                  name: 'Default',
                  builder: (context) => Padding(
                    padding: EdgeInsets.all(Theme.of(context).extension<IhGapExtension>()!.small3),
                    child: ElevatedButton(onPressed: (){

                      Navigator.of(context).push(MaterialPageRoute(
                          builder:  (context) => Test2()));
                    }, child: Text('press me')),
                  ),
                ),
              ],
            ),
          ],
        ),
      ],
    );
  }
}

class Test2 extends StatelessWidget {
  const Test2({super.key});

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: EdgeInsets.all(Theme.of(context).extension<IhGapExtension>()!.small3),
      child: ElevatedButton(onPressed:
          () {}, child: Text('press me')),
    );
  }
}
```

**Comment by yousinix** [comment] 2024-10-10 09:09
@andrewpmoore please provide us with a minimal **working** reproduction code. The code you posted above have a lot of references to external code, making it hard to debug/reproduce.

**Comment by andrewpmoore** [comment] 2024-10-10 13:26
@yousinix apologies, I thought I'd got rid of all the non-standard imports, here's a version without any

```
import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:widgetbook/widgetbook.dart';


void main() {
  runApp(const HotReload());
}

class HotReload extends StatefulWidget {
  const HotReload({super.key});

  @override
  State<HotReload> createState() => _HotReloadState();
}

class _HotReloadState extends State<HotReload> {
  @override
  Widget build(BuildContext context) {
    return Widgetbook.material(
      addons: [
        MaterialThemeAddon(
            themes: [
              WidgetbookTheme(
                name: 'Light',
                data: lightTheme(context),
              ),
            ]
        ),

      ],
      directories: [
        WidgetbookFolder(
          name: 'Example',
          children: [
            WidgetbookComponent(
              name: 'Text',
              useCases: [
                WidgetbookUseCase(
                  name: 'Default',
                  builder: (context) => Padding(
                    padding: EdgeInsets.all(Theme.of(context).extension<IhGapExtension>()!.small3),
                    child: ElevatedButton(onPressed: (){

                      Navigator.of(context).push(MaterialPageRoute(
                          builder:  (context) => Test2()));
                    }, child: Text('press me')),
                  ),
                ),
              ],
            ),
          ],
        ),
      ],
    );
  }
}

class Test2 extends StatelessWidget {
  const Test2({super.key});

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: EdgeInsets.all(Theme.of(context).extension<IhGapExtension>()!.small3),
      child: ElevatedButton(onPressed:
          () {}, child: Text('press me')),
    );
  }
}


IhGapExtension gapThemeDesktopExtension = const IhGapExtension(
  small3: 16,
);



@immutable
class IhGapExtension extends ThemeExtension<IhGapExtension> {
  const IhGapExtension({
    required this.small3,
  });

  final double small3;

  @override
  ThemeExtension<IhGapExtension> copyWith({
    double? small3,
  }) {
    return IhGapExtension(
      small3: small3 ?? this.small3,
    );
  }

  @override
  ThemeExtension<IhGapExtension> lerp(covariant ThemeExtension<IhGapExtension>? other, double t) {
    if (other == null || other.runtimeType != IhGapExtension) {
      return this;
    }
    final IhGapExtension typedOther = other as IhGapExtension;
    return IhGapExtension(
      small3: lerpDouble(small3, typedOther.small3, t)!,
    );
  }

  @override
  String toString() => 'IhTextThemeTheme('
      """small3: $small3"""
      ')';
}

ThemeData lightTheme(BuildContext context) {
  return ThemeData.light(useMaterial3: true).copyWith(
    extensions: <ThemeExtension<dynamic>>[
      gapThemeDesktopExtension,
    ],

  );
}




```

**Comment by yousinix** [comment] 2024-10-10 13:39
It seems like it is similar to the problem mentioned in #1222.
The `Theme.of(context)` in `Test2` is using the `Theme` from the `MaterialApp` in the root, and not the one from the `MaterialThemeAddon`. This is because you are pushing a route to the `MaterialApp`'s `Navigator`. You can find a detailed reason in [this comment](https://github.com/widgetbook/widgetbook/issues/1222#issuecomment-2275792891).

To fix this, you have to add another `Navigator` right above your use-case, or as the last addon in other words.

```dart
return Widgetbook.material(
  // ...
  addons: [
    MaterialThemeAddon(...),
    BuilderAddon(
      name: 'Navigator Addon',
      builder: (context, child) => Navigator(
        onGenerateRoute: (_) => PageRouteBuilder(
          pageBuilder: (context, _, __) => child,
        ),
      ),
    ),
  ],
);
```

**Closed by yousinix** 2024-10-10 13:39 UTC

**Comment by andrewpmoore** [comment] 2024-10-10 13:53
@yousinix perfect, thanks that helps
