### ISSUE TITLE
showDialog uses editor window and not device frame.

### ISSUE THREAD

**Issue by LeeHigginsExeter** [widgetbook/widgetbook#217] opened 2022-06-10 11:10 UTC
**Description**
When displaying dialogs they are not show at correct size in device preview 

**Steps To Reproduce**

1. using flutter create, make standard app
2. Call showDialog
3. Dialog size does not show correct size

**Expected Behavior**
Dialog appears within device frame bounds

**Comment by LeeHigginsExeter** [comment] 2022-06-10 11:25
You can fix this by calling showDialog(useRootNavigation:false ....) but that might not be what you want in production.

**Comment by jenshor** [comment] 2023-02-07 08:20
I'm able to reproduce the problem, however, I don't know what we as the package maintainers can do to help developers with this problem as `useRootNavigation: false` seems to be the solution/workaround. 

As a developer, I'd also not be happy with using `useRootNavigation: false` in production.

Since I'm not seeing any problems I'll label this as won't fix and close this issues. 

Feel free to re-open this issue if you have additional insights on how to fix this problem.

**Closed by jenshor** 2023-02-07 08:20 UTC
Labels: bug

**Comment by tieorange** [comment] 2024-01-03 17:27
This solution does not work with bottom sheet

It still is drawn outside of the device frame

Code:
`final result = await showModalBottomSheet(
    isScrollControlled: true,
    shape: const RoundedRectangleBorder(
      borderRadius: BorderRadius.vertical(top: Radius.circular(15)),
    ),
    barrierColor: kcBottomSheetBarrierColor,
    backgroundColor: kcWayfinderWhite,
    context: context,
    useRootNavigator: false,
    builder: (context) => child,
  );`

**Comment by pedrohba** [comment] 2024-05-21 10:52
I am facing the same issue with bottom sheet like @tieorange said. 

Do you have any update about this?

**Comment by YoussefRaafatNasry** [comment] 2024-05-21 10:58
Hello @pedrohba 👋 
Can you report the bottom sheet issue in a separate issue so that we can track it better?
