### ISSUE TITLE
How to use with Dart's monorepo configuration?

### ISSUE THREAD

**Issue by matthew-carroll** [widgetbook/widgetbook#1332] opened 2024-12-14 03:15 UTC
**Description**
Dart now supports a monorepo configuration through pubspec (as of version 3.6.0).

Based on my initial attempt to use Widgetbook, it looks like the `build_runner` step might not be compatible with it.

**Steps To Reproduce**

Create a project with a structure like:

```
my_mono_repo
  /packages
    /my_app
      pubspec.yaml
    /my_widget_book
      pubspec.yaml
    pubspec.yaml
```

Run `dart run build_runner build -d` within `my_mono_repo/packages/my_widget_book/`.

**Expected Behavior**
The use-cases are generated.

**Actual Behavior**
I'm getting the following error:

```
Building package executable... 
Built build_runner:build_runner.
[INFO] Generating build script completed, took 212ms
[INFO] Reading cached asset graph completed, took 165ms
[INFO] Checking for updates since last build completed, took 715ms
[INFO] Running build completed, took 14ms
[INFO] Caching finalized dependency graph completed, took 94ms
[SEVERE] widgetbook_generator:use_case_builder on lib/home/navigation_bars.dart (cached):

PathNotFoundException: Cannot open file, path = 'pubspec.lock' (OS Error: No such file or directory, errno = 2)
[SEVERE] Failed after 114ms
```

The error is that `pubspec.lock` is missing. Technically, this is true. There's no `pubspec.lock` within the `my_widget_book` directory. But that's because the mono-repo setup places the `pubspec.lock` in the root directory. In this case, that would be within the `my_mono_repo` directory.

I don't know if this is a general `build_runner` compatibility issue, or whether this is based on what Widgetbook is doing within the `build_runner`.

**Comment by yousinix** [comment] 2024-12-14 11:06
Hello @matthew-carroll 👋 
We shipped a hotfix (#1327) yesterday in `widgetbook_generator` [v3.9.1](https://pub.dev/packages/widgetbook_generator/versions/3.9.1) that solves this issue.

_(duplicate of #1326)_

**Closed by yousinix** 2024-12-14 11:06 UTC
