### ISSUE TITLE
Modal Bottom Sheet shows out of the device

### ISSUE THREAD

**Issue by dluksza** [widgetbook/widgetbook#1201] opened 2024-06-24 08:42 UTC
**Description**
The modal bottom sheet is not showing within the device mockup, instead it shows in the main widget scaffold.
**Steps To Reproduce**

1. Reproduction code:
```dart
import 'package:flutter/material.dart';
import 'package:widgetbook_annotation/widgetbook_annotation.dart' as widgetbook;

@widgetbook.UseCase(
  name: 'ModalBottomSheet',
  type: Center,
  path: 'modalBottomSheet',
)
Widget modalSeet(BuildContext context) {
  return Center(
    child: TextButton(
      onPressed: () {
        showModalBottomSheet(
          context: context,
          builder: (context) => const Padding(
            padding: EdgeInsets.all(8.0),
            child: Text("my modal bottom sheet"),
          ),
        );
      },
      child: const Text("show modal bottom sheet"),
    ),
  );
}
```
2. click on the button on the screen

**Expected Behavior**
The modal bottom sheet is shown within the device mockup

**Screenshots**
<img width="779" alt="Screenshot 2024-06-24 at 09 41 20" src="https://github.com/widgetbook/widgetbook/assets/127442/5ccc3825-335b-482c-8d8b-500daaea04e6">

**Comment by YoussefRaafatNasry** [comment] 2024-06-24 13:20
Hello @dluksza 👋 
Thanks for reporting this!

I was able to reproduce this issue. And I can also see that a similar problem happened in #172 with dialogs.

Since both [`showModalBottomSheet`](https://api.flutter.dev/flutter/material/showModalBottomSheet.html) and [`showDialog`](https://api.flutter.dev/flutter/material/showDialog.html) use the [`Navigator`](https://api.flutter.dev/flutter/widgets/Navigator-class.html), they are using the one that is being place via the [`appBuilder`](https://github.com/widgetbook/widgetbook/blob/5086582b8607498fd47400498144a3565d67c453/packages/widgetbook/lib/src/widgetbook.dart#L63-L64) in the [`Workbench`](https://github.com/widgetbook/widgetbook/blob/main/packages/widgetbook/lib/src/workbench/workbench.dart). This is how the Widget tree looks like _(simplified)_:

```tree
Workbench
└ appBuilder (MaterialApp)
  └ Navigator
    └ DeviceAddon
      └ UseCaseBuilder
        └ UseCase
```

To get this to work properly, the `Navigator` should be placed below the `DeviceAddon`. There might be some workarounds using either nested Navigators or using [`MaterialApp.builder`](https://api.flutter.dev/flutter/material/MaterialApp/builder.html) instead of [`MaterialApp.home`](https://api.flutter.dev/flutter/material/MaterialApp/home.html), but these solutions will take some time to test properly.

I will keep you posted once we have further updates.

**Comment by YoussefRaafatNasry** [comment] 2024-06-25 12:53
Great news, @dluksza!
We got a fix for this via the new `builder` parameter that was introduced in #1203.

Please, give it a try using the dependency below, and let us know if it solves your actual use-case issue _(not the reproduction code)_.

```yaml
dependencies:
  widgetbook:
    git:
      url: https://github.com/widgetbook/widgetbook.git
      path: packages/widgetbook/
      ref: feature/prd-1944-bottom-sheets-not-working-for-deviceframe
```

**Closed** 2024-07-11 10:49 UTC
Labels: t: bug, p: core
