### ISSUE TITLE
Failed to load font packages/widgetbook/Nunito

### ISSUE THREAD

**Issue by LeeHigginsExeter** [widgetbook/widgetbook#206] opened 2022-05-31 10:43 UTC
**Description**
Using the example code to create an app I get missing font errors in the console.
(it works but I think the fonts are not the ones intended)

**Steps To Reproduce**

1. Use example sample code from pub.dev
2. Use flutter pub add widgetbook to add the dependency
3. Run as web app using flutter run
4. Works but prints lots of font warnings

...
Failed to load font packages/widgetbook/Nunito at assets/packages/widgetbook/google_fonts/Nunito-Black.ttf
Verify that assets/packages/widgetbook/google_fonts/Nunito-Black.ttf contains a valid font.
...

**Expected Behavior**
Use intended fonts and not print warnings 

**Additional Context**
I tried adding the google fonts dependency to the app, but still had the issue.

**Comment by heavybeard** [comment] 2022-06-03 06:58
Same behavior here

**Comment by JensHor** [comment] 2022-06-03 07:49
Thanks @LeeHigginsExeter and @heavybeard for reporting this issue. While the warnings are certainly annoying, does this make Widgetbook unusable for you?

I'm assuming Flutter will default to another font in such a case.

**Comment by heavybeard** [comment] 2022-06-03 07:57
I will work on a fix in a few minutes, I have an idea because I faced the same problem with an app a few months ago.

Anyway Widgetbook is usable for me.

**Comment by JensHor** [comment] 2022-06-03 09:46
Ok, it's great that it's still usable. I assume the problem is that the fonts are defined in the package and are not properly 'exported' by the package which results in the missing fonts package. 

It would be great if you could fix this - we always love to see contributions 👍🏻

**Comment by heavybeard** [comment] 2022-06-03 13:42
@JensHor it's a pleasure to dedicate time to your project. The #211 PR is ready to review.

**Comment by JensHor** [comment] 2022-06-10 13:10
@heavybeard @momrak  We're currently busy doing other awesome stuff, but we'll merge the PR within the next week. We highly appreciate you, the community, in making Widgetbook better 💙 Sorry for the wait.

**Comment by momrak** [comment] 2022-07-04 13:23
@heavybeard did this fix work for you? I still get the same `Failed to load font...` messages. Anything I have to in order to get them away after bumping the widgetbook version?

**Comment by heavybeard** [comment] 2022-07-04 13:58
Oh wow, yeah... I still have the same message in the console.
It is really strange because I use the same font directory structure in my monorepo application, and it works.

I cannot work on it in next days, can you try to fix it @momrak?

I investigate a little bit and maybe here it is a fix from flutter, but it seems a verbose fix → https://docs.flutter.dev/cookbook/design/package-fonts#1-add-a-font-to-a-package

> To export a font from a package, you need to import the font files into the lib folder of the package project. You can place font files directly in the lib folder or in a subdirectory, such as lib/fonts.


 ```awesome_package/
 lib/
   widgetbook.dart
   fonts/
     Nunito-Regular.ttf
     Nunito-Italic.ttf
 ```

And the application can now use the font with 

```
flutter:
  fonts:
    - family: Nunito
      fonts:
        - asset: packages/widgetbook/fonts/Raleway-Regular.ttf
        - asset: packages/widgetbook/fonts/Raleway-Italic.ttf
          style: italic
```

**Comment by heavybeard** [comment] 2022-07-04 14:16
Using [`google_fonts`](https://pub.dev/packages/google_fonts) package could be another idea?

**Comment by vovaklh** [comment] 2022-10-08 08:11
Having the same problem
![image](https://user-images.githubusercontent.com/61093713/194697433-74d5163b-576e-44ba-bdb8-41376e798d08.png)

**Comment by evekeen** [comment] 2022-11-24 18:45
I have the same issue. And this ticket is marked as included in `2.4.1` release, but it's not!

**Comment by LucasJosefiak** [comment] 2023-03-08 09:36
The discord users `robotkins` and `ciochetta` also still have the issue. As soon as it's resolved, we'll ping them.

**Comment by YoussefRaafatNasry** [comment] 2023-06-16 13:13
This font was removed in #744

**Closed by YoussefRaafatNasry** 2023-06-16 13:13 UTC
Labels: bug
